### ISSUE TITLE
Add GPLv2+ license file

### ISSUE THREAD

**Issue by Crell** [WapplerSystems/messenger#1]
This repo has no license file, which means it's technically unlicensed, which means, strictly speaking, downloading it and using it is a felony. :smile: Since I assume that's not the intent of putting it here, please add a proper license.  Since this is a TYPO3 extension, GPLV2+ would be the proper license to use.

**Comment by svewap** [comment]
Ok, i thought the 
`"license": ["GPL-2.0-or-later"],`
in composer.json is enough. File added. Is it now ok?

**Comment by Crell** [comment]
Perfect, thanks.

I don't know that there's any legal standard on it.  (AFAIK, it's never been tested.)  But Github is picking up the file now, so that should definitely work either way.

Context for why I'm here: https://decisions.typo3.org/t/a-queue-in-core/739
